source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
# Ruby 3.4+ removed kconv from standard library
ruby ">= 2.6.10", "< 3.4.0"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
# CocoaPods version must match the version used to generate Podfile.lock (1.16.2)
gem 'cocoapods', '>= 1.16.2'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
# xcodeproj constraint removed - CocoaPods 1.16.2+ requires xcodeproj >= 1.27.0
gem 'concurrent-ruby', '< 1.3.4'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
